#! /bin/sh


bspc config border_width         2
bspc config window_gap          8 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true

bspc config history_aware_focus  true

bspc rule -a feh state=floating

sxhkd &

xsetroot -cursor_name left_ptr&
compton -bcC &
redshift &

# monitors and polybars
~/bin/mon.sh


#unclutter &
#nitrogen --set-scaled ~/Pictures/Wallpapers/winterTree.png
~/.fehbg
