#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true

bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off



~/src/lemonbar/lemonbar2.sh| lemonbar -fMonospace:size=10 -fFontAwesome:size=12 eDP1 | zsh & 

nitrogen --restore &
redshift &
compton -bcC &
